version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - run:
          name: Install packages
          command: npx lerna bootstrap
      - run:
          name: Run tests
          command: npx lerna run test
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_my_app:
    jobs:
      - build_and_test